set-environment -g PATH "/usr/local/bin:/bin:/usr/bin"
# List of plugins
set -g @plugin 'catppuccin/tmux#v2.1.0'
set -g @catppuccin_flavor 'mocha'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix


# Enable mouse support in Tmux
set-option -g mouse on

# Use Kitty's scroll events for native-like scrolling
bind -n WheelUpPane if-shell -F "#{mouse_any_flag}" "send-keys -M" "copy-mode -e"
bind -n WheelDownPane if-shell -F "#{mouse_any_flag}" "send-keys -M" "send-keys -M"

# Set scroll speed (optional)
set-option -g history-limit 10000

# Use Kitty's clipboard to copy selected text
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'kitty +kitten clipboard'
bind-key -T copy-mode y send -X copy-pipe-and-cancel 'kitty +kitten clipboard'



# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
